import React, { useState, useEffect, useCallback } from 'react';
import { supabase } from '../services/supabaseClient';
import { DatabaseTask } from '../types';
import { Plus, Trash2, Check, Circle, RefreshCw, AlertTriangle } from 'lucide-react';
import { Spinner } from './Spinner';

interface Props {
  userId: string;
  onNotify: (type: 'success' | 'error' | 'info', msg: string) => void;
}

export const TaskManager: React.FC<Props> = ({ userId, onNotify }) => {
  const [tasks, setTasks] = useState<DatabaseTask[]>([]);
  const [loading, setLoading] = useState(true);
  const [newTask, setNewTask] = useState('');
  const [adding, setAdding] = useState(false);
  const [tableError, setTableError] = useState(false);

  const fetchTasks = useCallback(async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('todos')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        if (error.code === '42P01') { // undefined_table
          setTableError(true);
        }
        throw error;
      }
      
      setTasks(data || []);
      setTableError(false);
    } catch (error: any) {
      console.error('Error fetching tasks:', error);
      // Don't notify for table missing, we handle it in UI
      if (error.code !== '42P01') {
        onNotify('error', 'Failed to fetch tasks');
      }
    } finally {
      setLoading(false);
    }
  }, [onNotify]);

  useEffect(() => {
    fetchTasks();
  }, [fetchTasks]);

  const addTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTask.trim()) return;
    
    setAdding(true);
    try {
      const { data, error } = await supabase
        .from('todos')
        .insert([{ title: newTask, user_id: userId, is_complete: false }])
        .select();

      if (error) throw error;

      if (data) {
        setTasks([data[0], ...tasks]);
        setNewTask('');
        onNotify('success', 'Task added successfully');
      }
    } catch (error: any) {
      onNotify('error', error.message);
    } finally {
      setAdding(false);
    }
  };

  const toggleTask = async (id: number, currentStatus: boolean) => {
    try {
      // Optimistic update
      setTasks(tasks.map(t => t.id === id ? { ...t, is_complete: !currentStatus } : t));

      const { error } = await supabase
        .from('todos')
        .update({ is_complete: !currentStatus })
        .eq('id', id);

      if (error) throw error;
    } catch (error: any) {
      onNotify('error', 'Failed to update task');
      fetchTasks(); // Revert on error
    }
  };

  const deleteTask = async (id: number) => {
    try {
      // Optimistic update
      setTasks(tasks.filter(t => t.id !== id));

      const { error } = await supabase
        .from('todos')
        .delete()
        .eq('id', id);

      if (error) throw error;
      onNotify('success', 'Task deleted');
    } catch (error: any) {
      onNotify('error', 'Failed to delete task');
      fetchTasks(); // Revert
    }
  };

  if (tableError) {
    return (
      <div className="p-6 bg-amber-500/10 border border-amber-500/20 rounded-xl">
        <div className="flex items-start gap-4">
          <AlertTriangle className="w-6 h-6 text-amber-500 shrink-0 mt-1" />
          <div>
            <h3 className="text-lg font-semibold text-amber-400 mb-2">Table "todos" Not Found</h3>
            <p className="text-amber-200/80 mb-4">
              To use this demo, you need to create a table in your Supabase project.
            </p>
            <div className="bg-black/50 p-4 rounded-lg font-mono text-sm text-slate-300 overflow-x-auto">
              <p className="mb-2 text-slate-500">// Run this in your Supabase SQL Editor</p>
              create table todos (<br/>
              &nbsp;&nbsp;id bigint generated by default as identity primary key,<br/>
              &nbsp;&nbsp;created_at timestamp with time zone default timezone('utc'::text, now()) not null,<br/>
              &nbsp;&nbsp;title text not null,<br/>
              &nbsp;&nbsp;is_complete boolean default false,<br/>
              &nbsp;&nbsp;user_id uuid references auth.users not null<br/>
              );<br/><br/>
              // Enable RLS if you want security<br/>
              alter table todos enable row level security;<br/>
              create policy "Individuals can create todos." on todos for insert with check (auth.uid() = user_id);<br/>
              create policy "Individuals can view their own todos." on todos for select using (auth.uid() = user_id);<br/>
              create policy "Individuals can update their own todos." on todos for update using (auth.uid() = user_id);<br/>
              create policy "Individuals can delete their own todos." on todos for delete using (auth.uid() = user_id);
            </div>
            <button 
              onClick={fetchTasks}
              className="mt-4 px-4 py-2 bg-amber-500 hover:bg-amber-600 text-slate-950 font-bold rounded-lg transition-colors"
            >
              I've created the table, Refresh
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-white">Your Tasks</h2>
        <button 
          onClick={fetchTasks} 
          disabled={loading}
          className="p-2 hover:bg-slate-800 rounded-full transition-colors text-slate-400 hover:text-white"
        >
          <RefreshCw className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      <form onSubmit={addTask} className="mb-8 relative">
        <input
          type="text"
          value={newTask}
          onChange={(e) => setNewTask(e.target.value)}
          placeholder="What needs to be done?"
          className="w-full py-4 pl-6 pr-16 bg-slate-900/50 border border-slate-800 rounded-xl text-lg text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 transition-all shadow-lg backdrop-blur-sm"
        />
        <button
          type="submit"
          disabled={adding || !newTask.trim()}
          className="absolute right-2 top-2 bottom-2 aspect-square bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 disabled:bg-slate-700 text-white rounded-lg flex items-center justify-center transition-all"
        >
          {adding ? <Spinner /> : <Plus className="w-6 h-6" />}
        </button>
      </form>

      <div className="space-y-3">
        {loading && tasks.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-slate-500">
             <Spinner className="w-8 h-8 mb-4 text-emerald-500" />
             <p>Loading your tasks...</p>
          </div>
        ) : tasks.length === 0 ? (
          <div className="text-center py-12 bg-slate-900/30 rounded-xl border border-slate-800 border-dashed">
            <p className="text-slate-400">No tasks yet. Add one above!</p>
          </div>
        ) : (
          tasks.map((task) => (
            <div 
              key={task.id}
              className="group flex items-center gap-4 p-4 bg-slate-900/40 border border-slate-800/50 hover:border-emerald-500/30 rounded-xl transition-all duration-200"
            >
              <button
                onClick={() => toggleTask(task.id, task.is_complete)}
                className={`shrink-0 w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors ${
                  task.is_complete 
                    ? 'bg-emerald-500 border-emerald-500 text-white' 
                    : 'border-slate-600 hover:border-emerald-500 text-transparent'
                }`}
              >
                <Check className="w-4 h-4" />
              </button>
              
              <span className={`flex-grow text-lg transition-colors ${
                task.is_complete ? 'text-slate-500 line-through decoration-slate-600' : 'text-slate-200'
              }`}>
                {task.title}
              </span>

              <button
                onClick={() => deleteTask(task.id)}
                className="opacity-0 group-hover:opacity-100 p-2 text-slate-500 hover:text-red-400 hover:bg-red-500/10 rounded-lg transition-all"
              >
                <Trash2 className="w-5 h-5" />
              </button>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
