
import React, { useState } from 'react';
import { Copy, Check, RefreshCw } from 'lucide-react';

export const SetupSQL: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const sqlScript = `
-- ==========================================
-- SCRIPT DE CORREÇÃO DEFINITIVA ECCLESIA
-- Execute este script COMPLETO no Supabase
-- ==========================================

-- 1. Extensões e Permissões Básicas
create extension if not exists "uuid-ossp";

-- Garante permissões CRÍTICAS para o funcionamento do cadastro público
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all privileges on all tables in schema public to postgres, anon, authenticated, service_role;
grant all privileges on all functions in schema public to postgres, anon, authenticated, service_role;
grant all privileges on all sequences in schema public to postgres, anon, authenticated, service_role;

-- 2. Função Auxiliar de Segurança
create or replace function public.get_my_church_id()
returns uuid as $$
  select igreja_id from public.profiles where id = auth.uid() limit 1
$$ language sql security definer;

-- 3. Criação de Tabelas (com verificação IF NOT EXISTS)

create table if not exists public.igrejas (
  id uuid primary key default uuid_generate_v4(),
  nome text not null,
  created_by uuid default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  igreja_id uuid references public.igrejas(id),
  role text default 'church_admin',
  full_name text
);

create table if not exists public.membros (
  id uuid primary key default uuid_generate_v4(),
  igreja_id uuid references public.igrejas(id) not null,
  full_name text not null,
  email text,
  phone text,
  birth_date date,
  role_type text default 'Member',
  status text default 'Active',
  address text,
  baptism_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.transacoes (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  description text not null,
  amount decimal(10,2) not null,
  type text check (type in ('income', 'expense')),
  category text,
  date date default current_date,
  member_id uuid references public.membros(id),
  supplier text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.ministerios (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  name text not null,
  description text,
  leader_id uuid references public.membros(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.discipulados (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  name text not null,
  description text,
  leader_name text, 
  meeting_day text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.reunioes_grupo (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  group_id bigint references public.discipulados(id) on delete cascade,
  date date default current_date,
  topic text,
  attendance_count integer default 0,
  observations text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.comunicados (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  type text check (type in ('email', 'sms')),
  subject text,
  content text not null,
  recipient_group text,
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.documentos (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  title text not null,
  type text check (type in ('minute', 'certificate')),
  content text, 
  document_date date default current_date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.avisos (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  title text not null,
  content text not null,
  priority text default 'Normal',
  expiration_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.midias (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  title text not null,
  type text check (type in ('Photo', 'Video', 'File')),
  url text not null,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.patrimonio (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  name text not null,
  description text,
  value decimal(10,2),
  acquisition_date date,
  location text,
  condition text default 'Good',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.ebd_classes (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  name text not null,
  teacher_name text,
  topic text,
  students_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.escalas (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  title text not null,
  date date not null,
  ministry_name text,
  volunteers text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.pedidos_oracao (
  id bigint generated by default as identity primary key,
  igreja_id uuid references public.igrejas(id) not null,
  requester_name text not null,
  request text not null,
  status text default 'Pending',
  is_public boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Atualização das Políticas de Segurança (RLS)

-- Habilita RLS em todas as tabelas
alter table public.igrejas enable row level security;
alter table public.profiles enable row level security;
alter table public.membros enable row level security;
alter table public.transacoes enable row level security;
alter table public.eventos enable row level security;
alter table public.ministerios enable row level security;
alter table public.discipulados enable row level security;
alter table public.reunioes_grupo enable row level security;
alter table public.comunicados enable row level security;
alter table public.documentos enable row level security;
alter table public.avisos enable row level security;
alter table public.midias enable row level security;
alter table public.patrimonio enable row level security;
alter table public.ebd_classes enable row level security;
alter table public.escalas enable row level security;
alter table public.pedidos_oracao enable row level security;

-- Remove políticas antigas para evitar conflitos
drop policy if exists "Enable insert for authenticated users only" on igrejas;
drop policy if exists "Enable select for own church" on igrejas;
drop policy if exists "Enable update for own church" on igrejas;
drop policy if exists "Users can manage own profile" on profiles;
drop policy if exists "Access members of own church" on membros;
drop policy if exists "Access finances of own church" on transacoes;
drop policy if exists "Access events of own church" on eventos;
drop policy if exists "Access ministries of own church" on ministerios;
drop policy if exists "Access groups of own church" on discipulados;
drop policy if exists "Access group meetings of own church" on reunioes_grupo;
drop policy if exists "Access coms of own church" on comunicados;
drop policy if exists "Access docs of own church" on documentos;
drop policy if exists "Access notices of own church" on avisos;
drop policy if exists "Access media of own church" on midias;
drop policy if exists "Access assets of own church" on patrimonio;
drop policy if exists "Access classes of own church" on ebd_classes;
drop policy if exists "Access scales of own church" on escalas;
drop policy if exists "Access prayers of own church" on pedidos_oracao;
drop policy if exists "Allow public insert" on membros;

-- Criação das Políticas

-- IGREJAS
create policy "Enable insert for authenticated users only" on igrejas 
for insert with check (auth.role() = 'authenticated');

create policy "Enable select for own church" on igrejas 
for select using (
  created_by = auth.uid() OR
  id = (select igreja_id from profiles where id = auth.uid() limit 1)
);

create policy "Enable update for own church" on igrejas 
for update using (
  created_by = auth.uid() OR
  id = (select igreja_id from profiles where id = auth.uid() limit 1)
);

-- PROFILES
create policy "Users can manage own profile" on profiles 
for all using (auth.uid() = id);

-- MEMBROS E LINK PÚBLICO
create policy "Access members of own church" on membros for all using (igreja_id = public.get_my_church_id());
-- ESTA É A POLÍTICA QUE PERMITE O CADASTRO PÚBLICO
create policy "Allow public insert" on membros for insert to anon with check (true);

-- DEMAIS TABELAS
create policy "Access finances of own church" on transacoes for all using (igreja_id = public.get_my_church_id());
create policy "Access events of own church" on eventos for all using (igreja_id = public.get_my_church_id());
create policy "Access ministries of own church" on ministerios for all using (igreja_id = public.get_my_church_id());
create policy "Access groups of own church" on discipulados for all using (igreja_id = public.get_my_church_id());
create policy "Access group meetings of own church" on reunioes_grupo for all using (igreja_id = public.get_my_church_id());
create policy "Access coms of own church" on comunicados for all using (igreja_id = public.get_my_church_id());
create policy "Access docs of own church" on documentos for all using (igreja_id = public.get_my_church_id());
create policy "Access notices of own church" on avisos for all using (igreja_id = public.get_my_church_id());
create policy "Access media of own church" on midias for all using (igreja_id = public.get_my_church_id());
create policy "Access assets of own church" on patrimonio for all using (igreja_id = public.get_my_church_id());
create policy "Access classes of own church" on ebd_classes for all using (igreja_id = public.get_my_church_id());
create policy "Access scales of own church" on escalas for all using (igreja_id = public.get_my_church_id());
create policy "Access prayers of own church" on pedidos_oracao for all using (igreja_id = public.get_my_church_id());

-- 5. Recarregar Cache do Supabase
NOTIFY pgrst, 'reload config';
  `;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-slate-950 flex items-center justify-center p-4">
      <div className="w-full max-w-5xl space-y-6 animate-in fade-in duration-500">
        
        <div className="bg-emerald-500/10 border border-emerald-500/30 p-6 rounded-xl flex items-start gap-4">
          <div className="p-2 bg-emerald-500/20 rounded-lg shrink-0">
            <Check className="w-6 h-6 text-emerald-500" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white mb-2">Correção Final de Sistema</h2>
            <p className="text-slate-300 mb-4 leading-relaxed">
              Este script contém todas as tabelas necessárias e as <strong>permissões públicas</strong> para o formulário de visitantes funcionar. Execute-o no Supabase SQL Editor.
            </p>
            <button 
              onClick={copyToClipboard}
              className={`flex items-center gap-2 px-6 py-3 rounded-lg transition-colors font-bold shadow-lg ${
                copied 
                  ? 'bg-emerald-600 text-white hover:bg-emerald-500' 
                  : 'bg-indigo-600 hover:bg-indigo-500 text-white'
              }`}
            >
              {copied ? <Check size={20} /> : <Copy size={20} />} 
              {copied ? 'Copiado!' : 'Copiar Script SQL'}
            </button>
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-2xl">
          <div className="p-3 bg-slate-950 border-b border-slate-800 flex justify-between items-center">
            <span className="text-xs font-mono text-slate-500">full_fix_v8.sql</span>
            <button onClick={() => window.location.reload()} className="text-xs flex items-center gap-1 text-indigo-400 hover:text-indigo-300">
                <RefreshCw size={12} /> Atualizar página
            </button>
          </div>
          <pre className="p-4 overflow-x-auto text-xs sm:text-sm font-mono text-slate-300 leading-relaxed h-[400px] overflow-y-auto selection:bg-indigo-500/30">
            {sqlScript}
          </pre>
        </div>
      </div>
    </div>
  );
};
